# Tennis pre-match prediction

## Test with a first dataset generate by a postegresql database and 3 tennis statistiques sources

In [194]:
# To support both python 2 and python 3
from __future__ import division, print_function, unicode_literals

# Common imports
import numpy as np
import pandas as pd
import os

# to make this notebook's output stable across runs
np.random.seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

# Where to save the figures
PROJECT_ROOT_DIR = "."

def save_fig(fig_id, tight_layout=True):
    path = os.path.join(PROJECT_ROOT_DIR, "images", fig_id + ".png")
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format='png', dpi=300)

### get data

##### CSV version

In [195]:
PATH = "dataset"
NAME = "dataset_train_final.csv"
PRED = "dataset_pred_final.csv"

def load_dataset_csv(path=PATH, name=NAME):
    csv_path = os.path.join(path, name)
    return pd.read_csv(csv_path)

def load_predictset_csv(path=PATH, name=PRED):
    csv_path = os.path.join(path, name)
    return pd.read_csv(csv_path)

##### SQL version

In [196]:
from sqlalchemy import create_engine
import psycopg2 as pg
import requests as req

URL = 'postgresql://dataset:dataset1747@35.204.62.91:5432/dataset-dump1'
engine = create_engine(URL)

def load_dataset_sql():
    URL = "https://raw.githubusercontent.com/panaC/tennis-dataset/master/app/dataset/extract_dataset.sql"
    with engine.connect() as conn, conn.begin():
        return pd.read_sql(req.get(URL).text, conn)

def load_predictset_sql():
    URL = "https://raw.githubusercontent.com/panaC/tennis-dataset/master/app/dataset/extract_predset.sql"
    with engine.connect() as conn, conn.begin():
        return pd.read_sql(req.get(URL).text, conn)


In [197]:
dataset = load_dataset_sql()
dataset.head()

id                            url_match_flash  \
0  30648  https://www.flashscore.com/match/zFScDpJb   
1  42244  https://www.flashscore.com/match/jcZcIiNh   
2  40048  https://www.flashscore.com/match/G00yITY5   
3  40071  https://www.flashscore.com/match/MPsuaWHS   
4    905  https://www.flashscore.com/match/8xr1BrDj   

                                    url_match_atp  \
0     /en/scores/archive/madrid/1536/2016/results   
1        /en/scores/archive/rome/416/2016/results   
2  /en/scores/archive/nottingham/741/2016/results   
3  /en/scores/archive/nottingham/741/2016/results   
4    /en/scores/archive/atlanta/6116/2016/results   

                                            url_tour name_tour_flash  \
0  https://www.flashscore.com/tennis/atp-singles/...          Madrid   
1  https://www.flashscore.com/tennis/atp-singles/...            Rome   
2  https://www.flashscore.com/tennis/atp-singles/...      Nottingham   
3  https://www.flashscore.com/tennis/atp-singles/...      Nottingham   
4  https://www.flashscore.com/tennis/atp-singles/...         Atlanta   

                        name_tour_atp name_tour_csv    round_flash round_csv  \
0  ATP World Tour Masters 1000 Madrid        Madrid  1/32-finals\n       R64   
1    ATP World Tour Masters 1000 Rome          Rome  1/32-finals\n       R64   
2                          Nottingham    Nottingham  1/16-finals\n       R32   
3                          Nottingham    Nottingham  1/32-finals\n       R64   
4                             Atlanta       Atlanta  1/16-finals\n       R32   

   qualif         ...          return_rating_20years  \
0   False         ...                       1.631293   
1   False         ...                     -27.924819   
2   False         ...                     -12.771137   
3   False         ...                     -20.714286   
4   False         ...                     -11.217407   

  first_serve_return_point_won_20years  bp_converted_20years  \
0                             2.059026             -2.284791   
1                            -4.775000            -13.214855   
2                            -2.217613             -4.413200   
3                            -2.142857            -17.285714   
4                             0.002116             -1.797011   

  return_games_played_20years  service_point_won_20years  \
0                   -0.099016                  -5.118173   
1                   -0.978261                 -15.291486   
2                   -0.862751                  -2.844315   
3                   -3.000000                  -1.000000   
4                    0.557619                   5.830450   

  return_point_won_20years total_point_won_20years winner_loser_match_win  \
0                 1.148676               -1.866266                    0.0   
1                -4.848007               -8.636051                    0.0   
2                -2.289802               -2.225344                    0.0   
3                -2.571429               -1.857143                    0.0   
4                -2.368942                1.484709                    0.0   

   h2h minutes_loser_winner  
0  1.0            -0.051257  
1  1.0             0.487892  
2  1.0            -0.000953  
3  1.0             0.654459  
4  1.0            -0.461002  

[5 rows x 91 columns]

In [198]:
predset = load_predictset_sql()
predset.head()

id                            url_match_flash  \
0  32463  https://www.flashscore.com/match/rNY1JN1J   
1  31626  https://www.flashscore.com/match/6ooVSMmN   
2  31714  https://www.flashscore.com/match/pEJHSi7R   
3  31702  https://www.flashscore.com/match/hOjYk3zo   
4  31703  https://www.flashscore.com/match/pjFsndOk   

                                   url_match_atp  \
0    /en/scores/archive/memphis/424/2017/results   
1  /en/scores/archive/marrakech/360/2017/results   
2  /en/scores/archive/marseille/496/2017/results   
3  /en/scores/archive/marseille/496/2017/results   
4  /en/scores/archive/marseille/496/2017/results   

                                            url_tour name_tour_flash  \
0  https://www.flashscore.com/tennis/atp-singles/...         Memphis   
1  https://www.flashscore.com/tennis/atp-singles/...       Marrakech   
2  https://www.flashscore.com/tennis/atp-singles/...       Marseille   
3  https://www.flashscore.com/tennis/atp-singles/...       Marseille   
4  https://www.flashscore.com/tennis/atp-singles/...       Marseille   

  name_tour_atp name_tour_csv    round_flash round_csv  qualif  \
0       Memphis       Memphis  1/16-finals\n       R32   False   
1     Marrakech     Marrakech  Semi-finals\n        SF   False   
2     Marseille     Marseille   1/8-finals\n       R16   False   
3     Marseille     Marseille        Final\n         F   False   
4     Marseille     Marseille  Semi-finals\n        SF   False   

          ...          return_rating_20years  \
0         ...                       6.002359   
1         ...                      -7.844612   
2         ...                     -20.197581   
3         ...                      -9.615572   
4         ...                      20.109863   

  first_serve_return_point_won_20years  bp_converted_20years  \
0                            -0.957381              5.242706   
1                            -1.403509              1.253968   
2                            -2.246334             -9.619048   
3                            -3.607057             -3.547220   
4                             4.511465              5.104797   

  return_games_played_20years  service_point_won_20years  \
0                   -0.004762                   1.178377   
1                    0.340852                  -0.273183   
2                   -0.412547                 -10.933107   
3                    0.161451                  -5.439763   
4                   -1.269387                   3.497913   

  return_point_won_20years total_point_won_20years winner_loser_match_win  \
0                -0.043485                0.377143                    1.0   
1                -2.252924               -1.174603                    1.0   
2                -2.142555               -6.141421                    0.0   
3                -1.780724               -3.190885                    2.0   
4                 4.027860                3.203217                    1.0   

   h2h minutes_loser_winner  
0  0.0            -0.276590  
1  0.5             0.069335  
2  1.0             0.069351  
3  0.0                  NaN  
4  0.6             0.074847  

[5 rows x 91 columns]

In [199]:
predset.shape

(3761, 91)

In [200]:
dataset.shape

(34148, 91)

In [201]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34148 entries, 0 to 34147
Data columns (total 91 columns):
id                                      34148 non-null int64
url_match_flash                         34148 non-null object
url_match_atp                           34148 non-null object
url_tour                                34148 non-null object
name_tour_flash                         34148 non-null object
name_tour_atp                           34148 non-null object
name_tour_csv                           34148 non-null object
round_flash                             34148 non-null object
round_csv                               34148 non-null object
qualif                                  34148 non-null bool
door                                    34148 non-null object
surface                                 34148 non-null object
prize                                   34148 non-null int64
year_atp                                34148 non-null object
year_flash                 

In [202]:
# to make this notebook's output identical at every run
np.random.seed(42)

### split the training set and the test set into 2 batchs with the hash id

In [203]:
import hashlib

def test_set_check(identifier, test_ratio, hash=hashlib.md5):
    return bytearray(hash(np.int64(identifier)).digest())[-1] < 256 * test_ratio

def split_train_test_by_id(data, test_ratio, id_column):
    ids = data[id_column]
    in_test_set = ids.apply(lambda id_: test_set_check(id_, test_ratio))
    return data.loc[~in_test_set], data.loc[in_test_set]

In [204]:
train_set, test_set = split_train_test_by_id(dataset, 0.2, "id")

In [205]:
print(train_set.shape)
train_set.head()

(27148, 91)


id                            url_match_flash  \
0  30648  https://www.flashscore.com/match/zFScDpJb   
2  40048  https://www.flashscore.com/match/G00yITY5   
3  40071  https://www.flashscore.com/match/MPsuaWHS   
4    905  https://www.flashscore.com/match/8xr1BrDj   
6  57660  https://www.flashscore.com/match/drhJu0R2   

                                       url_match_atp  \
0        /en/scores/archive/madrid/1536/2016/results   
2     /en/scores/archive/nottingham/741/2016/results   
3     /en/scores/archive/nottingham/741/2016/results   
4       /en/scores/archive/atlanta/6116/2016/results   
6  /en/scores/archive/winston-salem/6242/2016/res...   

                                            url_tour name_tour_flash  \
0  https://www.flashscore.com/tennis/atp-singles/...          Madrid   
2  https://www.flashscore.com/tennis/atp-singles/...      Nottingham   
3  https://www.flashscore.com/tennis/atp-singles/...      Nottingham   
4  https://www.flashscore.com/tennis/atp-singles/...         Atlanta   
6  https://www.flashscore.com/tennis/atp-singles/...   Winston-Salem   

                        name_tour_atp  name_tour_csv    round_flash round_csv  \
0  ATP World Tour Masters 1000 Madrid         Madrid  1/32-finals\n       R64   
2                          Nottingham     Nottingham  1/16-finals\n       R32   
3                          Nottingham     Nottingham  1/32-finals\n       R64   
4                             Atlanta        Atlanta  1/16-finals\n       R32   
6                       Winston-Salem  Winston-Salem  1/16-finals\n       R32   

   qualif         ...          return_rating_20years  \
0   False         ...                       1.631293   
2   False         ...                     -12.771137   
3   False         ...                     -20.714286   
4   False         ...                     -11.217407   
6   False         ...                     -24.155651   

  first_serve_return_point_won_20years  bp_converted_20years  \
0                             2.059026             -2.284791   
2                            -2.217613             -4.413200   
3                            -2.142857            -17.285714   
4                             0.002116             -1.797011   
6                            -3.991762             -6.441762   

  return_games_played_20years  service_point_won_20years  \
0                   -0.099016                  -5.118173   
2                   -0.862751                  -2.844315   
3                   -3.000000                  -1.000000   
4                    0.557619                   5.830450   
6                    0.786303                  -0.790709   

  return_point_won_20years total_point_won_20years winner_loser_match_win  \
0                 1.148676               -1.866266                    0.0   
2                -2.289802               -2.225344                    0.0   
3                -2.571429               -1.857143                    0.0   
4                -2.368942                1.484709                    0.0   
6                -4.116092               -2.654502                    2.0   

   h2h minutes_loser_winner  
0  1.0            -0.051257  
2  1.0            -0.000953  
3  1.0             0.654459  
4  1.0            -0.461002  
6  0.2             0.270004  

[5 rows x 91 columns]

In [206]:
print(test_set.shape)
test_set.head()

(7000, 91)


id                            url_match_flash  \
1   42244  https://www.flashscore.com/match/jcZcIiNh   
5   11572  https://www.flashscore.com/match/tjWesBmN   
15  16168  https://www.flashscore.com/match/SCeQru63   
20   6713  https://www.flashscore.com/match/SfK5pURK   
21  15056  https://www.flashscore.com/match/vg2Z57xB   

                                       url_match_atp  \
1           /en/scores/archive/rome/416/2016/results   
5     /en/scores/archive/cincinnati/422/2016/results   
15          /en/scores/archive/doha/451/2008/results   
20        /en/scores/archive/bastad/316/2013/results   
21  /en/scores/archive/delray-beach/499/2015/results   

                                             url_tour name_tour_flash  \
1   https://www.flashscore.com/tennis/atp-singles/...            Rome   
5   https://www.flashscore.com/tennis/atp-singles/...      Cincinnati   
15  https://www.flashscore.com/tennis/atp-singles/...            Doha   
20  https://www.flashscore.com/tennis/atp-singles/...          Bastad   
21  https://www.flashscore.com/tennis/atp-singles/...    Delray Beach   

                             name_tour_atp name_tour_csv       round_flash  \
1         ATP World Tour Masters 1000 Rome          Rome     1/32-finals\n   
5   ATP World Tour Masters 1000 Cincinnati    Cincinnati     Semi-finals\n   
15                                    Doha          Doha     Semi-finals\n   
20                                  Bastad        Bastad     1/16-finals\n   
21                            Delray Beach  Delray Beach  Quarter-finals\n   

   round_csv  qualif         ...          return_rating_20years  \
1        R64   False         ...                     -27.924819   
5         SF   False         ...                     -41.138750   
15        SF   False         ...                     -17.518324   
20       R32   False         ...                      40.425170   
21        QF   False         ...                       8.973000   

   first_serve_return_point_won_20years  bp_converted_20years  \
1                             -4.775000            -13.214855   
5                             -7.388578             -5.345927   
15                            -3.023477             -3.507222   
20                             7.717347              6.785374   
21                             2.178111             -1.823889   

   return_games_played_20years  service_point_won_20years  \
1                    -0.978261                 -15.291486   
5                     0.495614                   6.118737   
15                   -0.570255                  -2.045622   
20                   -1.143197                  -2.169388   
21                   -1.868222                  -6.641889   

   return_point_won_20years total_point_won_20years winner_loser_match_win  \
1                 -4.848007               -8.636051                    0.0   
5                 -8.897202               -1.424943                    3.0   
15                -3.413699               -2.469572                    3.0   
20                 8.471769                2.895238                    0.0   
21                 3.478333               -2.047778                    0.0   

         h2h minutes_loser_winner  
1   1.000000             0.487892  
5   0.454545            -0.064994  
15  0.250000             0.316686  
20  1.000000                  NaN  
21  1.000000             0.338504  

[5 rows x 91 columns]

In [207]:
dataset = train_set.copy()

In [208]:
dataset["draw_size"] = dataset["draw_size"].apply(lambda x: str(x))
dataset["draw_size"] = dataset["draw_size"].astype("object")
index_draw_size = list(dataset["draw_size"].value_counts().index)
dataset["draw_size"].value_counts()

32     9754
128    4758
28     3155
56     3120
48     2549
96     1990
64     1737
8        74
16       11
Name: draw_size, dtype: int64

In [209]:
index_level_tour = list(dataset["level_tour"].value_counts().index)
dataset["level_tour"].value_counts()

A    16240
M     6233
G     4590
F       85
Name: level_tour, dtype: int64

In [210]:
index_surface = list(dataset["surface"].value_counts().index)
dataset["surface"].value_counts()

Hard      15239
Clay       8119
Grass      3231
Carpet      559
Name: surface, dtype: int64

In [211]:
index_door = list(dataset["door"].value_counts().index)
dataset["door"].value_counts()

Outdoor    22498
Indoor      4650
Name: door, dtype: int64

In [212]:
index_round_csv = list(dataset["round_csv"].value_counts().index)
dataset["round_csv"].value_counts()

R32     9529
R16     5100
R64     4937
R128    3039
QF      2552
SF      1293
F        627
RR        71
Name: round_csv, dtype: int64

In [213]:
dataset["year_atp"].value_counts()

2016    1906
2009    1826
2014    1798
2010    1792
2006    1785
2011    1774
2005    1764
2013    1745
2012    1727
2004    1727
2008    1719
2007    1705
2003    1658
2001    1590
2002    1572
2015    1060
Name: year_atp, dtype: int64

### add column result that will be the y axis on the dataset for the prediction

In [214]:
dataset.shape

(27148, 91)

In [215]:
dataset.insert(dataset.shape[1], "result", np.random.randint(2, size=dataset.shape[0]))

In [216]:
dataset["result"].value_counts()

1    13585
0    13563
Name: result, dtype: int64

In [217]:
test_set.insert(test_set.shape[1], "result", np.random.randint(2, size=test_set.shape[0]))

In [218]:
test_set["result"].value_counts()

1    3535
0    3465
Name: result, dtype: int64

### transformer

In [219]:
from sklearn.base import BaseEstimator, TransformerMixin

# A class to select numerical or categorical columns 
# since Scikit-Learn doesn't handle DataFrames yet
class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names]

In [220]:
class reverseStats(BaseEstimator, TransformerMixin):
       
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):
        ## while on each row : if result = 1 nothing else opponent each value in each collumn
        def wh(a):
            if (a["result"] == 0):
                a = a.apply(lambda x: x * -1)
            return a
        
        X = X.fillna(0)
        X = X.apply(wh, axis=1)
        X = X.drop("result", axis=1)
        return X

In [221]:
stats_col = ["serve_rating_1year", "aces_1year", "double_faults_1year", "first_serve_1year", "first_serve_point_won_1year",
       "second_serve_point_won_1year", "bp_saved_1year", "service_game_played_1year", "return_rating_1year",
       "first_serve_return_point_won_1year", "bp_converted_1year", "return_games_played_1year", "service_point_won_1year",
       "return_point_won_1year", "total_point_won_1year", "serve_rating_20years",
       "aces_20years", "double_faults_20years", "first_serve_20years", "first_serve_point_won_20years", "second_serve_point_won_20years",
       "bp_saved_20years", "service_game_played_20years", "return_rating_20years", "first_serve_return_point_won_20years",
       "bp_converted_20years", "return_games_played_20years", "service_point_won_20years", "return_point_won_20years",
       "total_point_won_20years", "h2h", "minutes_loser_winner", "result"]
len(stats_col)

33

In [222]:
from sklearn.pipeline import Pipeline

stats_pipeline = Pipeline([
        ("select_stats", DataFrameSelector(stats_col)),
        ("reverse", reverseStats()),
    ])

stats_pipeline.fit_transform(dataset).shape

(27148, 32)

In [223]:
stats_pipeline.fit_transform(dataset)

serve_rating_1year  aces_1year  double_faults_1year  first_serve_1year  \
0               22.680874   -1.353279            -0.859836           8.912022   
2               -6.668889   -1.328148             0.091852          -2.805926   
3               15.666667    1.666667             2.666667          -0.000000   
4              -17.928571   -5.785714            -0.428571           3.142857   
6               12.351282   -5.203846            -0.489744           7.125321   
7              -18.353409   -4.653409            -0.875758           2.303788   
8               70.226190    7.142857            -1.130952           5.142857   
9               12.619211    0.216533             0.910997           5.292173   
10             -28.925223   -4.390253             2.524330           0.473437   
11              -2.760000    1.307415            -0.039048          -1.938231   
12               3.183059   -6.966392            -2.358852           8.609417   
13             -15.372953    0.937427            -0.627339          -4.621053   
14               0.458225   -0.296050             0.237635          -3.945671   
16              48.040292    0.343161            -2.199782           8.098888   
17              -8.989354   -1.820860            -0.403192          -0.158523   
18             -18.981481    5.064815             0.981481          -3.296296   
19             -41.194203   -4.696377            -1.065217          -6.203623   
22              -7.166667   -0.273810             0.059524           0.936508   
23             -11.643411   -0.515504             0.957364           0.290698   
24             -17.962963    0.169753            -0.922840          -7.986111   
25              -5.536765   -1.281863             1.568627           0.377451   
26              -1.942308    3.147436             0.262821           3.839744   
27             -17.757687   -3.441624             0.347050          -0.428061   
28             -59.000000   -6.941176             0.029412          -1.264706   
29              66.250000    3.250000            -7.250000           5.750000   
30             -21.912863   -0.929704             0.114954           4.408653   
31             -17.857143   -0.571429            -1.357143          -4.071429   
32               0.000000    0.000000             0.000000           0.000000   
33              13.535380   -0.739181            -2.824561           8.489766   
34               0.000000    0.000000             0.000000           0.000000   
...                   ...         ...                  ...                ...   
34112           19.490643    1.328363            -0.362865          -1.978947   
34113           -8.917708   -1.684375            -0.636458          -0.900000   
34114          -29.523770   -5.727643             1.334153           3.622619   
34115          -27.282813   -2.324890             2.789886          -8.875360   
34116           45.023611    6.227778            -1.484722          -7.474653   
34117           17.829545   -1.429924            -0.056818           5.017045   
34118          -36.429762   -3.016270            -0.027778          -7.359524   
34119            3.106831   -4.228223             0.270624           1.608743   
34120            7.943434    2.119192             0.668939          -0.108838   
34121           39.000000    3.500000             1.500000           4.500000   
34122           11.562500    0.105882            -0.462500           5.988725   
34123           14.319876    2.615528             0.181435          -1.183126   
34124            1.485139    1.955521             0.851936          -6.183726   
34125          -17.053252   -3.658537             1.589024           6.770325   
34126           -4.834565   -0.771899            -0.200055          -2.747093   
34127           24.666667    0.166667             0.166667          -2.111111   
34129          -23.943478   -3.600564             1.186151          -7.350483   
34130          -36.780556   -5.243576 

In [224]:
from sklearn.preprocessing import OneHotEncoder, LabelBinarizer
from sklearn.preprocessing import label_binarize

In [225]:
class CustomLabelBinarizer(BaseEstimator, TransformerMixin):
    def __init__(self, classes):
        self.classes = classes
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):
        enc = label_binarize(X, classes=self.classes)
        return enc

In [226]:
round_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["round_csv"])),
        ("cat_encoder", CustomLabelBinarizer(index_round_csv)),
    ])

round_pipeline.fit_transform(dataset)

array([[0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [227]:
round_pipeline.fit_transform(dataset).shape

(27148, 8)

In [228]:
surface_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["surface"])),
        ("cat_encoder", CustomLabelBinarizer(index_surface)),
    ])

surface_pipeline.fit_transform(dataset)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       ...,
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0]])

In [229]:
surface_pipeline.fit_transform(dataset).shape

(27148, 4)

In [230]:
drawSize_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["draw_size"])),
        ("cat_encoder", CustomLabelBinarizer(index_draw_size)),
    ])

drawSize_pipeline.fit_transform(dataset)

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [231]:
drawSize_pipeline.fit_transform(dataset).shape

(27148, 9)

In [232]:
levelTour_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["level_tour"])),
        ("cat_encoder", CustomLabelBinarizer(index_level_tour)),
    ])

levelTour_pipeline.fit_transform(dataset)

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       ...,
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0]])

In [233]:
levelTour_pipeline.fit_transform(dataset).shape

(27148, 4)

In [234]:
from sklearn.preprocessing import Imputer

weather_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["temp_weather", "press_weather", "humid_weather"])),
        ('imputer', Imputer(strategy="mean")),
    ])

weather_pipeline.fit_transform(dataset)

array([[ 61.  ,  27.52,  55.  ],
       [ 65.  ,  29.49,  80.  ],
       [ 68.  ,  29.72,  81.  ],
       ...,
       [ 63.  ,  30.13,  88.  ],
       [ 60.  ,  29.64,  91.  ],
       [ 45.  ,  27.82, 100.  ]])

In [235]:
weather_pipeline.fit_transform(dataset).shape

(27148, 3)

In [236]:
from sklearn.preprocessing import Imputer

year_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["year_atp"])),
        ('imputer', Imputer(strategy="most_frequent")),
    ])

year_pipeline.fit_transform(dataset)

array([[2016.],
       [2016.],
       [2016.],
       ...,
       [2016.],
       [2016.],
       [2016.]])

In [237]:

year_pipeline.fit_transform(dataset).shape

(27148, 1)

In [238]:
class CustomLabelBinarizer(BaseEstimator, TransformerMixin):
    def __init__(self, sparse_output=False):
        self.sparse_output = sparse_output
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):
        enc = LabelBinarizer(sparse_output=self.sparse_output)
        return enc.fit_transform(X)

In [239]:
door_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["door"])),
        ("cat_encoder", CustomLabelBinarizer()),
    ])

door_pipeline.fit_transform(dataset)

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [240]:
door_pipeline.fit_transform(dataset).shape

(27148, 1)

In [241]:
class fillna(BaseEstimator, TransformerMixin):
    def __init__(self, val):
        self.val = val
        
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):        
        return X.fillna(self.val)

In [242]:
uncertainty_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["uncertainty_1year", "uncertainty_20years"])),
        ("cat_encoder", fillna(10)),
    ])

uncertainty_pipeline.fit_transform(dataset).shape

(27148, 2)

In [243]:
count_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["count_match_1year", "count_match_20years"])),
        ("cat_encoder", fillna(0)),
    ])

count_pipeline.fit_transform(dataset).shape

(27148, 2)

In [244]:
from sklearn.pipeline import FeatureUnion
preprocess_pipeline = FeatureUnion(transformer_list=[
        ("stats_pipeline", stats_pipeline),
        ("round_pipeline", round_pipeline),
        ("surface_pipeline", surface_pipeline),
        ("drawSize_pipeline", drawSize_pipeline),
        ("levelTour_pipeline", levelTour_pipeline),
        ("weather_pipeline", levelTour_pipeline),
        ("year_pipeline", levelTour_pipeline),
        ("door_pipeline", levelTour_pipeline),
        ("uncertainty_pipeline", levelTour_pipeline),
        ("count_pipeline", count_pipeline),
    ])

In [245]:
X_train = preprocess_pipeline.fit_transform(dataset)

In [246]:
X_train.shape

(27148, 75)

In [247]:
pd.DataFrame(X_train).head()

0         1         2         3         4         5          6   \
0  22.680874 -1.353279 -0.859836  8.912022 -0.228962  4.176776  -0.974317   
1  -6.668889 -1.328148  0.091852 -2.805926 -0.319630 -1.348519  -1.214815   
2  15.666667  1.666667  2.666667 -0.000000  4.333333  0.333333  14.666667   
3 -17.928571 -5.785714 -0.428571  3.142857 -8.142857  7.500000  -4.071429   
4  12.351282 -5.203846 -0.489744  7.125321 -1.542949  6.682372   8.243269   

         7          8         9   ...     65   66   67   68   69   70   71  \
0  0.684973  -6.111202 -2.769672  ...    0.0  1.0  0.0  0.0  0.0  1.0  0.0   
1 -1.078889  -6.271481 -1.893704  ...    1.0  0.0  0.0  0.0  1.0  0.0  0.0   
2  4.666667  33.000000  6.333333  ...    1.0  0.0  0.0  0.0  1.0  0.0  0.0   
3 -2.071429  13.285714  2.428571  ...    1.0  0.0  0.0  0.0  1.0  0.0  0.0   
4 -0.016987  16.787179  2.906731  ...    1.0  0.0  0.0  0.0  1.0  0.0  0.0   

    72     73     74  
0  0.0  110.0  243.0  
1  0.0   71.0  130.0  
2  0.0    3.0    7.0  
3  0.0   10.0  200.0  
4  0.0   75.0  148.0  

[5 rows x 75 columns]

In [248]:
pd.DataFrame(X_train).isnull().any().value_counts()

False    75
dtype: int64

In [249]:
y_train = dataset["result"]
y_train.shape

(27148,)

#### predset preprocess

In [250]:
testset = test_set.copy()

In [251]:
X_test = preprocess_pipeline.fit_transform(testset)
y_test = testset["result"]

### KNN

In [252]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

param_grid = [{'weights': ["uniform", "distance"], 'n_neighbors': [3, 4, 5]}]

knn_clf = KNeighborsClassifier()
grid_search = GridSearchCV(knn_clf, param_grid, cv=5, verbose=3, n_jobs=-1)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] n_neighbors=3, weights=uniform ..................................
[CV] n_neighbors=3, weights=uniform ..................................
[CV] n_neighbors=3, weights=uniform ..................................
[CV] n_neighbors=3, weights=uniform ..................................
[CV]  n_neighbors=3, weights=uniform, score=0.6572112727942531, total=   2.1s
[CV] n_neighbors=3, weights=uniform ..................................
[CV]  n_neighbors=3, weights=uniform, score=0.6500920810313076, total=   2.1s
[CV] n_neighbors=3, weights=distance .................................
[CV]  n_neighbors=3, weights=uniform, score=0.6497237569060773, total=   2.1s
[CV] n_neighbors=3, weights=distance .................................
[CV]  n_neighbors=3, weights=uniform, score=0.6469613259668509, total=   2.2s
[CV] n_neighbors=3, weights=distance .................................
[CV]  n_neighbors=3, weights=distance, score=0.6546961325966

[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:  1.3min finished


GridSearchCV(cv=5, error_score='raise',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid=[{'weights': ['uniform', 'distance'], 'n_neighbors': [3, 4, 5]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [253]:
grid_search.best_params_

{'n_neighbors': 5, 'weights': 'distance'}

In [254]:
grid_search.best_score_

0.664689848239281

In [255]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_jobs=-1, weights='uniform', n_neighbors=3)
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=-1, n_neighbors=3, p=2,
           weights='uniform')

In [256]:
y_knn_pred = knn_clf.predict(X_train)

from sklearn.metrics import accuracy_score
accuracy_score(y_train, y_knn_pred)

0.8195078827169588

### RF

In [257]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

forest_clf = RandomForestClassifier(random_state=42)
forest_clf.fit(X_train, y_train)
forest_scores = cross_val_score(forest_clf, X_train, y_train, cv=10, n_jobs=-1)
forest_scores.mean()

0.8375564129443569

In [258]:
forest_clf_pred = forest_clf.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, forest_clf_pred)

0.836

### saved the model on the disk

In [259]:
import pickle

PATH = 'models/'

def save_model(obj, name, path=PATH):
    file = open(path + name, 'wb')
    pickle.dump(obj, file)
    file.close()

save_model(forest_clf, "forest_clf")

### GridSearch

In [260]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_distribs = {
        'n_estimators': randint(low=100, high=500),
        'max_features': randint(low=5, high=15),
    }

forest_reg = RandomForestClassifier(random_state=42)
rnd_search = RandomizedSearchCV(forest_reg, param_distributions=param_distribs,
                                n_iter=10, cv=5, scoring='neg_mean_squared_error', random_state=42, n_jobs=-1)
rnd_search.fit(X_train, y_train) 

RandomizedSearchCV(cv=5, error_score='raise',
          estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False),
          fit_params=None, iid=True, n_iter=10, n_jobs=-1,
          param_distributions={'n_estimators': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fe901579710>, 'max_features': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fe8dee27710>},
          pre_dispatch='2*n_jobs', random_state=42, refit=True,
          return_train_score='warn', scoring='neg_mean_squared_error',
          verbose=0)

In [261]:
rnd_search.best_params_

{'max_features': 14, 'n_estimators': 314}

In [262]:
feature_importances = rnd_search.best_estimator_.feature_importances_
#sorted(zip(feature_importan)ces, list(dataset.columns.values)), reverse=True))
feature_importances[32:] ## useless

array([1.74523258e-03, 1.59797413e-03, 1.28461142e-03, 8.79527716e-04,
       1.29364500e-03, 1.16683467e-03, 9.87311221e-04, 7.13805457e-05,
       1.66380151e-03, 1.74338495e-03, 1.27144517e-03, 5.40166838e-04,
       1.48346600e-03, 7.26739057e-04, 1.21437177e-03, 1.34053176e-03,
       1.27236443e-03, 9.35057097e-04, 1.05660824e-03, 5.63673761e-05,
       4.86983061e-05, 8.37696766e-04, 8.02484718e-04, 6.47551913e-04,
       7.43099759e-05, 8.43781548e-04, 8.31686466e-04, 6.68131734e-04,
       7.64290157e-05, 8.62079098e-04, 8.06828381e-04, 6.53943354e-04,
       6.78264716e-05, 8.62368260e-04, 7.52145664e-04, 6.47294889e-04,
       5.51692092e-05, 8.54230546e-04, 7.88949216e-04, 6.95053883e-04,
       6.44439995e-05, 3.13948044e-02, 3.76958812e-02])

In [263]:
from sklearn.metrics import accuracy_score

rnd_pred = rnd_search.predict(X_train)

accuracy_score(y_train, rnd_pred)

1.0

In [264]:
save_model(rnd_search, "rnd_search")

### predset

match beetween years 2017 and 2018

In [265]:
valset = predset.copy()

valset.insert(valset.shape[1], "result", np.random.randint(2, size=valset.shape[0]))
valset["result"].value_counts()

X_val = preprocess_pipeline.fit_transform(valset)
y_val = valset["result"]

In [266]:
forest_clf_pred = forest_clf.predict(X_val)

from sklearn.metrics import accuracy_score
accuracy_score(y_val, forest_clf_pred)

0.8548258441903749

 - 85% of prediction accuracy , the almosts bookmakers are about 60% with odds modulation

In [267]:
from sklearn.metrics import accuracy_score

rnd_pred = rnd_search.predict(X_val)

accuracy_score(y_val, rnd_pred)

0.86838606753523

### Test with only Common Opponent

In [268]:
X_train = stats_pipeline.fit_transform(dataset)
y_train = dataset["result"]

In [269]:
X_test = stats_pipeline.fit_transform(test_set)
y_test = test_set["result"]

In [270]:
X_val = stats_pipeline.fit_transform(valset)
y_val = valset["result"]

In [271]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_distribs = {
        'n_estimators': randint(low=100, high=500),
        'max_features': randint(low=5, high=15),
    }

forest_reg = RandomForestClassifier(random_state=42)
rnd_search_co = RandomizedSearchCV(forest_reg, param_distributions=param_distribs,
                                n_iter=10, cv=5, scoring='neg_mean_squared_error', random_state=42, n_jobs=-1)
rnd_search_co.fit(X_train, y_train) 

RandomizedSearchCV(cv=5, error_score='raise',
          estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False),
          fit_params=None, iid=True, n_iter=10, n_jobs=-1,
          param_distributions={'n_estimators': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fe8da26f2b0>, 'max_features': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fe8da26f438>},
          pre_dispatch='2*n_jobs', random_state=42, refit=True,
          return_train_score='warn', scoring='neg_mean_squared_error',
          verbose=0)

In [272]:
rnd_search_co.best_params_

{'max_features': 6, 'n_estimators': 443}

In [273]:
feature_importances = rnd_search_co.best_estimator_.feature_importances_
#sorted(zip(feature_importan)ces, list(dataset.columns.values)), reverse=True))
feature_importances[32:] ## useless

array([], dtype=float64)

In [274]:
from sklearn.metrics import accuracy_score

rnd_pred_co = rnd_search_co.predict(X_test)
accuracy_score(y_test, rnd_pred_co)

0.8045714285714286

In [275]:
rnd_pred_co = rnd_search_co.predict(X_val)
accuracy_score(y_val, rnd_pred_co)

0.8516352034033502

In [276]:
save_model(rnd_search_co, "rnd_search_co")

## Prediction pre-match 11/10/18

In [277]:
import pickle

PATH = 'models/'

def load_model(name, path=PATH):
    file = open(path + name, 'rb')
    obj = pickle.load(file)
    file.close()
    return obj

model = load_model("rnd_search_co")

In [278]:
from sqlalchemy import create_engine
import psycopg2 as pg
import requests as req

URL = 'postgresql://dataset:dataset1747@35.204.62.91:5432/dataset-dump1'
engine = create_engine(URL)

def get_data_prediction(date, winner, looser):
    URL = "https://raw.githubusercontent.com/panaC/tennis-dataset/master/app/dataset/prediction.sql"
    with engine.connect() as conn, conn.begin():
        return pd.read_sql(req.get(URL).text.format(date=date, winner=winner, looser=looser), conn)

In [ ]:
prediction_data = get_data_prediction('11/10/2018', 'Stefanos Tsitsipas', 'Alex de Minaur')
prediction_data

In [279]:
prediction_data.insert(prediction_data.shape[1], "result", np.random.randint(2, size=prediction_data.shape[0]))

X_pred = stats_pipeline.fit_transform(prediction_data)
pred = model.predict(X_pred)

In [280]:
model.predict_proba(X_pred)

array([[0.06320542, 0.93679458]])

In [281]:
prediction_data["result"][0]

1

In [282]:
pred[0]

1

There is 97% of probability that Tsitsipas win because the result is 1 and 1 = first player in fct

In [283]:
prediction_data = get_data_prediction('11/10/2018', 'Kevin Anderson', 'Dominic Thiem')
prediction_data

uncertainty_1year  count_match_1year  serve_rating_1year  aces_1year  \
0           0.067935                 13             -15.825       -5.65   

   double_faults_1year  first_serve_1year  first_serve_point_won_1year  \
0                  1.6          -6.716667                        2.075   

   second_serve_point_won_1year  bp_saved_1year  service_game_played_1year  \
0                      0.516667           5.975                  -0.333333   

           ...           return_rating_20years  \
0          ...                        9.790835   

   first_serve_return_point_won_20years  bp_converted_20years  \
0                              3.092286              0.669302   

   return_games_played_20years  service_point_won_20years  \
0                     -0.72378                  -2.896813   

   return_point_won_20years  total_point_won_20years  winner_loser_match_win  \
0                  2.132079                -0.335131                     0.0   

   h2h  minutes_loser_winner  
0  1.0                  None  

[1 rows x 37 columns]

In [284]:
prediction_data.insert(prediction_data.shape[1], "result", np.random.randint(2, size=prediction_data.shape[0]))

X_pred = stats_pipeline.fit_transform(prediction_data)
pred = model.predict(X_pred)

In [285]:
model.predict_proba(X_pred)

array([[0.07900677, 0.92099323]])

In [286]:
prediction_data["result"][0]

1

In [287]:
pred[0]

1

- warning combine option. I think that 1 year is too short for head2head , add 3 new colonne with may be 10 years combine

In [288]:
prediction_data = get_data_prediction('11/10/2018', 'Alexander Zverev', 'Marin Cilic')
prediction_data

uncertainty_1year  count_match_1year  serve_rating_1year  aces_1year  \
0           0.091912                 15           14.346154    4.230769   

   double_faults_1year  first_serve_1year  first_serve_point_won_1year  \
0            -1.076923          -2.961538                     3.153846   

   second_serve_point_won_1year  bp_saved_1year  service_game_played_1year  \
0                      1.115385        3.538462                   1.538462   

           ...           return_rating_20years  \
0          ...                        3.321875   

   first_serve_return_point_won_20years  bp_converted_20years  \
0                              0.985911             -0.114494   

   return_games_played_20years  service_point_won_20years  \
0                     0.206544                    3.67691   

   return_point_won_20years  total_point_won_20years  winner_loser_match_win  \
0                  0.968995                  2.11016                     1.0   

        h2h  minutes_loser_winner  
0  0.666667                  None  

[1 rows x 37 columns]

In [289]:
prediction_data.insert(prediction_data.shape[1], "result", np.random.randint(2, size=prediction_data.shape[0]))

X_pred = stats_pipeline.fit_transform(prediction_data)
pred = model.predict(X_pred)

In [290]:
model.predict_proba(X_pred)

array([[0.78329571, 0.21670429]])

In [291]:
prediction_data["result"][0]

0

In [292]:
pred[0]

0

In [293]:
prediction_data = get_data_prediction('11/10/2018', 'Novak Djokovic', 'John Isner')
prediction_data

uncertainty_1year  count_match_1year  serve_rating_1year  aces_1year  \
0            0.15625                  8              39.625      20.625   

   double_faults_1year  first_serve_1year  first_serve_point_won_1year  \
0                  1.0              3.125                        9.375   

   second_serve_point_won_1year  bp_saved_1year  service_game_played_1year  \
0                      -11.6875         21.5625                     7.5625   

           ...           return_rating_20years  \
0          ...                      -68.709553   

   first_serve_return_point_won_20years  bp_converted_20years  \
0                            -13.003473            -14.844916   

   return_games_played_20years  service_point_won_20years  \
0                     2.604565                   3.238263   

   return_point_won_20years  total_point_won_20years  winner_loser_match_win  \
0                -14.168259                -5.131055                     2.0   

        h2h  minutes_loser_winner  
0  0.333333                  None  

[1 rows x 37 columns]

In [294]:
prediction_data.insert(prediction_data.shape[1], "result", np.random.randint(2, size=prediction_data.shape[0]))

X_pred = stats_pipeline.fit_transform(prediction_data)
pred = model.predict(X_pred)

In [295]:
model.predict_proba(X_pred)

array([[0.66817156, 0.33182844]])

In [296]:
prediction_data["result"][0]

0

In [297]:
pred[0]

0

if prediction_data["result"][0] == 0 then 
    
    pred = 1 = los or pred = 0 = winner 

else

    pred = 1 = win or pred = 0 = los